version: '3'
services:
  strapi:
    container_name: strapi
    build: ./strapi
    image: ts-strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: 'postgres'
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    platform: linux/amd64 # platform error on Apple M1
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ # data volume
    ports:
      - '5432:5432'
    networks:
      - strapi

  nextjs:
    container_name: nextjs
    build: ./next
    image: ts-nextjs:latest
    restart: unless-stopped
    ports:
      - '3000:3000'

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
